### ISSUE TITLE
Version 2.0.5 does not contain dist folder

### ISSUE THREAD

**Issue by jbpenrath** [aykutkardas/react-icomoon#10]
Since version 2.0.5, there is no dist in the package.
<img width="138" alt="Capture d’écran 2020-04-23 à 21 57 00" src="https://user-images.githubusercontent.com/9265241/80143679-7b23c680-85ad-11ea-9021-6d0079d6e97e.png">

No problem with version 2.0.4

**Comment by aykutkardas** [comment]
This is crazy. 

This issue has been fixed with this release. v2.0.6

Thank you for reporting this.
