### ISSUE TITLE
react-native support?

### ISSUE THREAD

**Issue by kockok** [aykutkardas/react-icomoon#12]
Hello, is this package compatible with react native?
I cannot get it work.

**Comment by aykutkardas** [comment]
> Hello, is this package compatible with react native?
> I cannot get it work.

There are too many requirements to view an svg format on React-Native. React-Icomoon does not work on React Native. It is for the web only. @kockok

**Comment by aykutkardas** [comment]
As of version 2.2.2 this is now possible. @kockok Check README.
