### ISSUE TITLE
Not find path name

### ISSUE THREAD

**Issue by adrielcardoso** [aykutkardas/react-icomoon#2]
![screenshot_1550086416](https://user-images.githubusercontent.com/5895482/52738344-98c2cc80-2fb5-11e9-9ebe-be7bc9a7871e.png)

**Comment by aykutkardas** [comment]
If you want to use the icon on the "React-Native", it is usually recommended to turn the icons to the font. You can check out this post. This package does not work in "React-Native". Only for ReactJS. 

[Logicwind — How to use svg icons in react-native](http://blog.logicwind.com/how-to-use-svg-icons-in-react-native/)

@adrielcardoso

**Comment by aykutkardas** [comment]
As of version 2.2.2, you can now use it with React-Native. @adrielcardoso Check README.
