### ISSUE TITLE
Fix static height value of viewBox

### ISSUE THREAD

**Issue by aykutkardas** [aykutkardas/react-icomoon#22]
https://github.com/aykutkardas/react-icomoon/blob/master/src/index.tsx#L66

Current:
```js
 props.viewBox = `0 0 ${width} 1024`;
```

Expected:
```js
 props.viewBox = `0 0 ${width} ${width}`;
```

**Comment by aykutkardas** [comment]
This change may cause some problems. Suspended for now.

**Comment by jtraub** [comment]
@aykutkardas what problems can it cause?

**Comment by aykutkardas** [comment]
> @aykutkardas what problems can it cause?

Icons are taken from icomoon at a fixed height. This prevents this part from being dynamic. Because only a limited part of the icon is visible.

I was working on an alternative svg parser tool to Icomoon and so I wanted to do it but I don't need it anymore. So it's a trivial issue and now react-icomoon works pretty stable.
