### ISSUE TITLE
RNWeb: The style props works only with Inline style

### ISSUE THREAD

**Issue by karthick-t2s** [aykutkardas/react-icomoon#23]
In RNWeb, The `style` property works only as an inline style. It didn't work if it's passed as an object from `StyleSheet.create({})`

Here is an expo link, switch to `web` tab and see the issue. working fine in iOS & Android

https://snack.expo.dev/@heykarthick/react-icomoon

```
import * as React from 'react';
import { View, StyleSheet } from 'react-native';

import Icon from './components/Icon';
const styles = StyleSheet.create({
  iconStyle: {
    color: 'red',
    margin: 20,
  },
});
export default function App() {
  return (
    <View>
      <Icon icon="pencil" size={100} style={styles.iconStyle} /> {/* didn't work */}
      <Icon icon="pencil" size={100} style={{ color: 'red', margin: 20 }} /> {/*Works*/}
    </View>
  );
}
```

**Comment by aykutkardas** [comment]
You're right. I will work on it. Thanks for your feedback.

**Comment by karthick-t2s** [comment]
Hey, thanks, and please note that the array of styles is also not working for the web.  
eg:
` style={[styles.defaultStyle,styles.customStyle]}`

**Comment by aykutkardas** [comment]
> Hey, thanks, and please note that the array of styles is also not working for the web. eg: ` style={[styles.defaultStyle,styles.customStyle]}`

Why not just use it as an object?
```js
const styles = {
  iconStyle: {
    margin: 50,
    color: 'red',
  },
};
```

For Expo, this usage may be the exception.
