### ISSUE TITLE
Update react peerDependencies version

### ISSUE THREAD

**Issue by Eugene-Musika** [aykutkardas/react-icomoon#28]
Currently react version mentioned in package.json is "^16.4.1"
```json
 "peerDependencies": {
    "react": "^16.4.1"
  },
```
and it causes error while installing package for react >=17.0.0 with npm. Not a big issue, but you must every time add flag --legacy-peer-deps

I suppose that it will work fine if change peer deps version to this
```json
 "peerDependencies": {
    "react": ">=16.4.1 <18.0.0-0"
  },
```

**Comment by aykutkardas** [comment]
Closed with #27
