### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by ithustle** [aykutkardas/react-icomoon#5]
Is it possible using this lib add new icons?

**Comment by aykutkardas** [comment]
Not yet. Currently it only allows you to use the standard icons provided by icomoon. I can add this as a feature.

**Comment by ithustle** [comment]
Good. It will be a good asset...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aykutkardas** [comment]
@ithustle You can check the repo. Npm package was updated. 
https://github.com/aykutkardas/React-IcoMoon#custom-iconset

**Comment by ithustle** [comment]
@aykutkardas , I've checked and tried it but I have this error:

![Screenshot_1575289623](https://user-images.githubusercontent.com/5114680/69959449-7d568d00-1507-11ea-8974-7577b747fdc2.png)

**Comment by aykutkardas** [comment]
> @aykutkardas , I've checked and tried it but I have this error:

@ithustle Oh. Sorry. This package is only suitable for web projects. You have to follow a different way to use icons in Mobile.

Please check this repo. https://github.com/oblador/react-native-vector-icons#createiconsetfromicomoonconfig-fontfamily-fontfile

**Comment by ithustle** [comment]
Ouch!! It's okay. No problem. Thanks anyway
