### ISSUE TITLE
Add types for typescript

### ISSUE THREAD

**Issue by iezepov** [aykutkardas/react-icomoon#9]
It's always nice to have type information and it would be great to have type information for this awesome package.

I'm thinking to create @types/react-icomoon or maybe even better to just re-write this project (well, single js file) to TypeScript. Then users will know props just from autocompletion for example.

What do you think?

**Comment by aykutkardas** [comment]
A great idea. Instead of creating a dependency for this small component or rewriting this component with **typescript**, it can be sufficient to create only an `index.d.ts` file.

**Comment by davidkhierl** [comment]
any pr for this?

**Comment by aykutkardas** [comment]
> any pr for this?

No for now. If there is no help from the community, I will solve it this week. @davidkhierl

**Comment by davidkhierl** [comment]
> > any pr for this?
> 
> No for now. If there is no help from the community, I will solve it this week. @davidkhierl

seems the recent publish are not properly typed hence had some problem in my project so I made a pr to fully type the project.
#13

**Comment by aykutkardas** [comment]
I'm sorry it's so late. TypeScript support is now ready.

[v2.3.0](https://github.com/aykutkardas/react-icomoon/releases/tag/v2.3.0)
